-- 1)SELECIONAR TODOS OS ATORES DO FILME COM O CÓDIGO 50

SELECT * FROM filme_ator
WHERE filme_id = 50;

-- 2)FAÇA UMA CONSULTA QUE RETORNE APENAS O NOME DO ATOR CAMERON STREEP

SELECT * FROM ator 
WHERE primeiro_nome = 'CAMERON'
 AND ultimo_nome = 'STREEP'

-- 3)FAÇA UMA CONSULTA QUE RETORNE TODOS OS ATORES POR ORDEM DE NOME INVERTIDA.

SELECT * FROM ator 
ORDER BY primeiro_nome DESC;

-- 4)VERIFIQUE NA TABELA ATOR QUANTOS SOBRENOMES EXISTEM SEM REPETIÇÃO

SELECT DISTINCT ultimo_nome FROM ator;
 
-- 5) FAÇA UMA CONSULTA QUE RETORNE OS 50 PRIMEIROS NOMES DE FILMES EM ORDEM ALFABÉTICA
SELECT * FROM filme 
WHERE filme_id <= 50
 ORDER BY titulo ASC;
